- name: prepare the ec2 to jenkins slave
  hosts: test1
  become: true
  tasks:
    - name: update
      apt:
        update_cache: yes
    - name: create directory
      file:
        path: /home/ubuntu/jenkins-home/
        state: directory
        mode: "0777"
    - name: install open openjdk
      apt:
        name: openjdk-11-jdk
